## Comparativa List y Numpy

In [1]:
from random import randint

In [2]:
L = [1,3,4,5,6,7]
L

[1, 3, 4, 5, 6, 7]

In [3]:
L2 = [randint(1,10) for _ in range(len(L))]
L2

[2, 5, 2, 9, 4, 2]

In [4]:
R = []
for i, item in enumerate(L):
    R.append(L[i]+L2[i])
R
    

[3, 8, 6, 14, 10, 9]

In [5]:
import numpy as np

In [6]:
a1 = np.array(L)
a1

array([1, 3, 4, 5, 6, 7])

In [7]:
a2 = np.random.randint(1,10,len(L))
a2

array([8, 1, 5, 3, 1, 3])

In [8]:
R2 = a1 + a2
R2

array([ 9,  4,  9,  8,  7, 10])

In [9]:
m =  np.random.randint(1,25, (10,8))
m

array([[20, 24, 15,  1,  8, 20,  7, 16],
       [22, 20, 22,  8, 22, 14, 14, 11],
       [18, 22, 10, 18, 14,  7, 21, 20],
       [ 3,  1,  2, 23, 10, 13, 12, 20],
       [11,  4, 17,  1,  6, 23,  3, 20],
       [15, 13, 11,  1,  4, 15,  4, 15],
       [13, 14, 12, 16, 12,  5,  6, 17],
       [ 9,  2, 12, 22, 20,  8, 11, 17],
       [ 7, 13, 14,  4,  2,  2, 19,  8],
       [15, 23,  2, 18, 22, 21, 18, 17]])

In [11]:
m2 =  np.random.randint(1,25, (10,8))
m2

array([[11, 12, 13,  3,  2, 17, 16, 15],
       [23, 24,  4,  5, 20, 17, 11, 21],
       [ 3,  1, 20, 15, 22, 18,  8,  8],
       [22,  7,  8, 14,  8, 20,  2,  7],
       [ 5, 24, 23, 12, 16, 11, 15, 15],
       [12,  6, 23, 20,  8,  6,  6, 13],
       [17,  5, 24, 11, 16, 15,  8, 11],
       [12, 23,  1, 13,  7,  3, 20, 24],
       [ 7, 23,  2, 21, 23,  1,  4, 19],
       [16, 13,  9, 14, 24,  8, 12, 24]])

In [13]:
suma = m + m2
suma

array([[31, 36, 28,  4, 10, 37, 23, 31],
       [45, 44, 26, 13, 42, 31, 25, 32],
       [21, 23, 30, 33, 36, 25, 29, 28],
       [25,  8, 10, 37, 18, 33, 14, 27],
       [16, 28, 40, 13, 22, 34, 18, 35],
       [27, 19, 34, 21, 12, 21, 10, 28],
       [30, 19, 36, 27, 28, 20, 14, 28],
       [21, 25, 13, 35, 27, 11, 31, 41],
       [14, 36, 16, 25, 25,  3, 23, 27],
       [31, 36, 11, 32, 46, 29, 30, 41]])

In [14]:
L1 = [1,2,3,4,5,6]
L2 = [7,5,4,3,2,1]

L1 + L2

[1, 2, 3, 4, 5, 6, 7, 5, 4, 3, 2, 1]