## Comparativa List y Numpy

In [3]:
from random import randint

In [1]:
L = [1,3,4,5,6,7]
L

[1, 3, 4, 5, 6, 7]

In [4]:
L2 = [randint(1,10) for _ in range(len(L))]
L2

[3, 8, 1, 4, 7, 4]

In [5]:
R = []
for i, item in enumerate(L):
    R.append(L[i]+L2[i])
R
    

[4, 11, 5, 9, 13, 11]

In [6]:
import numpy as np

In [7]:
a1 = np.array(L)
a1

array([1, 3, 4, 5, 6, 7])

In [8]:
a2 = np.random.randint(1,10,len(L))
a2

array([3, 5, 8, 9, 9, 2])

In [9]:
R2 = a1 + a2
R2

array([ 4,  8, 12, 14, 15,  9])