# Pruebas con Python

Pruebas con código para el curso

In [1]:
from random import randint
import numpy as np

In [2]:
L1 = [randint(1,10) for _ in range(10)]
L2 = [randint(1,10) for _ in range(10)]

In [3]:
L1

[4, 7, 9, 4, 8, 9, 5, 1, 2, 2]

In [4]:
L2

[1, 9, 1, 7, 3, 10, 8, 10, 4, 5]

In [5]:
Lsuma = []
for pos, i in  enumerate(L1):
    Lsuma.append(L1[pos]+L2[pos])
Lsuma

[5, 16, 10, 11, 11, 19, 13, 11, 6, 7]

In [6]:
L1 + L2

[4, 7, 9, 4, 8, 9, 5, 1, 2, 2, 1, 9, 1, 7, 3, 10, 8, 10, 4, 5]

In [7]:
arr1 = np.array(L1)
arr2 = np.array(L2)

In [8]:
arr1

array([4, 7, 9, 4, 8, 9, 5, 1, 2, 2])

In [9]:
arr1 + arr2

array([ 5, 16, 10, 11, 11, 19, 13, 11,  6,  7])

In [10]:
a = arr1 * 10
a

array([40, 70, 90, 40, 80, 90, 50, 10, 20, 20])

In [11]:
m = np.arange(50).reshape(2, 5,-1)
m

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [12]:
m2 = np.arange(50).reshape(2, 5,-1)
m2

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [13]:
m + m2

array([[[ 0,  2,  4,  6,  8],
        [10, 12, 14, 16, 18],
        [20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38],
        [40, 42, 44, 46, 48]],

       [[50, 52, 54, 56, 58],
        [60, 62, 64, 66, 68],
        [70, 72, 74, 76, 78],
        [80, 82, 84, 86, 88],
        [90, 92, 94, 96, 98]]])

In [14]:
m.shape

(2, 5, 5)

In [15]:
m.T

array([[[ 0, 25],
        [ 5, 30],
        [10, 35],
        [15, 40],
        [20, 45]],

       [[ 1, 26],
        [ 6, 31],
        [11, 36],
        [16, 41],
        [21, 46]],

       [[ 2, 27],
        [ 7, 32],
        [12, 37],
        [17, 42],
        [22, 47]],

       [[ 3, 28],
        [ 8, 33],
        [13, 38],
        [18, 43],
        [23, 48]],

       [[ 4, 29],
        [ 9, 34],
        [14, 39],
        [19, 44],
        [24, 49]]])

In [16]:
b = np.exp(Lsuma)
b

array([1.48413159e+02, 8.88611052e+06, 2.20264658e+04, 5.98741417e+04,
       5.98741417e+04, 1.78482301e+08, 4.42413392e+05, 5.98741417e+04,
       4.03428793e+02, 1.09663316e+03])

In [17]:
np.round(b, 2)

array([1.48410000e+02, 8.88611052e+06, 2.20264700e+04, 5.98741400e+04,
       5.98741400e+04, 1.78482301e+08, 4.42413390e+05, 5.98741400e+04,
       4.03430000e+02, 1.09663000e+03])

In [18]:
b.sum()

188014122.24175546

In [19]:
a = np.array([1,5,6,7,5,55,44,22,11])
a[a > 20]

array([55, 44, 22])

In [20]:
b = np.array([1,5,6,-7,5,-55,-44,22,11])
a == b

array([ True,  True,  True, False,  True, False, False,  True,  True])

In [21]:
m = np.corrcoef(a,b)
m

array([[ 1.        , -0.83552989],
       [-0.83552989,  1.        ]])

In [22]:
porc = m[1][0]
porc *= 100
porc

-83.55298905941274

In [23]:
a = np.array([10, 33, 55,11,44])

b = np.array([12, 13, 45,51,44])

np.maximum(a,b)

array([12, 33, 55, 51, 44])

In [24]:
np.minimum(a,b)

array([10, 13, 45, 11, 44])